const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
const fake=`export async function createFirebaseService(config){
const empty=()=>({version:1,changes:{}}),initial=empty();let draft=empty(),current=empty(),cb,head=0;window.__fixture={saves:0,failNext:false};const rerender=()=>window.__fixture.publicCallback?.(current);
return {bucket:config.storageBucket,observeAuth(fn){cb=fn;setTimeout(()=>fn(null),0);return()=>{};},subscribePublic(fn){window.__fixture.publicCallback=fn;fn(current);},async isOwner(user){return user.email==='owner@nexori.test';},async login(email){await cb({uid:'owner',email,emailVerified:true});},async logout(){await cb(null);},async resetPassword(){},async verifyEmail(){},async loadDraft(){return structuredClone(draft);},async save(payload){if(window.__fixture.failNext){window.__fixture.failNext=false;throw Object.assign(new Error('Conflict'),{code:'functions/aborted'});}await new Promise(r=>setTimeout(r,20));draft=structuredClone(payload);window.__fixture.saves++;},async publish(){current=structuredClone(draft);head++;rerender();},async restore(){current=initial;head++;rerender();},async published(){return structuredClone(current);},async revisions(){return [{id:'initial',revision:0},{id:'12345678-1234-1234-1234-123456789abc',revision:head}];},clear(){}};}`;
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{const ctx=await b.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
await p.route('**/src/firebase-config.js*',r=>r.fulfill({contentType:'application/javascript',body:'export function firebaseConfiguration(){return null;}'}));await p.goto('http://127.0.0.1:5173/admin');await p.getByRole('heading',{name:'ניהול NEXORI'}).waitFor();assert.match(await p.locator('#firebase-admin-page').textContent(),/עדיין לא חיברנו/);assert.equal(await p.locator('.owner-toolbar').count(),0);assert.equal(await p.locator('.owner-edit-button').count(),0);
await p.route('**/src/firebase-config.js*',r=>r.fulfill({contentType:'application/javascript',body:`export function firebaseConfiguration(){return {apiKey:'demo-key',projectId:'demo-nexori',authDomain:'demo-nexori.firebaseapp.com',storageBucket:'demo-nexori.appspot.com',appId:'demo-app'};}`}));
await p.route('**/src/firebase-service.js*',r=>r.fulfill({contentType:'application/javascript',body:fake}));
await p.reload();await p.locator('#admin-login-form').waitFor();await p.locator('[name=email]').fill('outsider@nexori.test');await p.locator('[name=password]').fill('password123');await p.evaluate(()=>window.__fixture.publicCallback({version:1,changes:{}}));assert.equal(await p.locator('[name=email]').inputValue(),'outsider@nexori.test');assert.equal(await p.locator('[name=password]').inputValue(),'password123');await p.locator('#admin-login-form [type=submit]').click();await p.getByRole('heading',{name:'החשבון אינו מורשה לעריכה'}).waitFor();assert.equal(await p.locator('.owner-edit-button').count(),0);await p.locator('[data-admin-logout]').click();await p.locator('#admin-login-form').waitFor();
await p.locator('[name=email]').fill('owner@nexori.test');await p.locator('[name=password]').fill('password123');await p.locator('#admin-login-form [type=submit]').click();await p.locator('.owner-toolbar').waitFor();await p.getByRole('heading',{name:'מצב עריכה פעיל'}).waitFor();await p.getByRole('link',{name:'מעבר לאתר ולכפתורי העריכה'}).click();await p.locator('.hero .owner-edit-button').waitFor();
assert.equal(await p.locator('[data-owner-export]').isVisible(),false);
// Full document reload intentionally resets this in-memory mock. Sign in again, then navigate internally.
await p.goto('http://127.0.0.1:5173/admin');await p.locator('#admin-login-form').waitFor();await p.locator('[name=email]').fill('owner@nexori.test');await p.locator('[name=password]').fill('password123');await p.locator('#admin-login-form [type=submit]').click();await p.locator('.owner-toolbar').waitFor();
await p.getByRole('link',{name:'Anime worlds',exact:true}).first().click();
for(const id of ['one-piece','naruto','demon-slayer','jujutsu-kaisen','dragon-ball','attack-on-titan']){assert.equal(await p.locator(`[data-content-id="${id}"]`).count(),1);const shell=p.locator(`[data-content-id="${id}"]`).locator('..');await shell.locator('.owner-edit-button').click();assert.equal(await p.locator('[name=cardTitle]').count(),1);assert.equal(await p.locator('[name=pageTitle]').count(),1);await p.getByRole('button',{name:'ביטול',exact:true}).click();}
await p.locator('[data-content-id="dragon-ball"]').click();await p.locator('.franchise-banner>.owner-edit-button').click();await p.locator('[name=pageTitle]').fill('Dragon Ball Universe');await p.locator('[type=submit]').click();await p.locator('#owner-editor-dialog').waitFor({state:'hidden'});assert.equal(await p.locator('h1').textContent(),'Dragon Ball Universe');assert.match(await p.locator('.owner-status').textContent(),/Firebase/);assert.equal(await p.evaluate(()=>localStorage.getItem('nexori.owner-draft.v1')),null);
await p.getByRole('link',{name:'Anime worlds',exact:true}).first().click();assert.equal(await p.locator('[data-content-id="dragon-ball"] h3').textContent(),'Dragon Ball');await p.locator('[data-content-id="dragon-ball"]').click();
await p.locator('.franchise-banner>.owner-edit-button').click();await p.locator('[name=pageTitle]').fill('Failed edit');await p.evaluate(()=>window.__fixture.failNext=true);await p.locator('[type=submit]').click();await p.getByRole('alert').filter({hasText:'ממכשיר אחר'}).waitFor();assert.equal(await p.locator('h1').textContent(),'Dragon Ball Universe');await p.getByRole('button',{name:'ביטול',exact:true}).click();
await p.locator('[data-cloud-publish]').click();await p.locator('.owner-status').filter({hasText:'הוחלו באתר'}).waitFor();
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'workspace width '+width);await p.locator('.franchise-banner>.owner-edit-button').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'dialog width '+width);await p.keyboard.press('Escape');}
await p.setViewportSize({width:1440,height:1000});await p.locator('[data-admin-logout]').click();await p.locator('.owner-toolbar').waitFor({state:'detached'});assert.equal(await p.locator('.owner-edit-button').count(),0);assert.equal(await p.locator('h1').textContent(),'Dragon Ball Universe');
await p.getByRole('link',{name:'Owner sign-in',exact:true}).click();await p.locator('#admin-login-form').waitFor();await p.locator('[name=email]').fill('owner@nexori.test');await p.locator('[name=password]').fill('password123');await p.locator('#admin-login-form [type=submit]').click();await p.locator('.owner-toolbar').waitFor();await p.locator('[data-cloud-revisions]').selectOption('initial');await p.locator('[data-cloud-restore]').click();await p.locator('.owner-status').filter({hasText:'שוחזרה'}).waitFor();await p.locator('[data-cloud-load-public]').click();await p.locator('.owner-status').filter({hasText:'כטיוטה חדשה'}).waitFor();await p.getByRole('link',{name:'Anime worlds',exact:true}).first().click();await p.locator('[data-content-id="dragon-ball"]').click();assert.equal(await p.locator('h1').textContent(),'Dragon Ball');
await p.screenshot({path:process.env.NEXORI_ADMIN_SCREENSHOT || '/tmp/nexori-firebase-admin-preview.png',fullPage:false});assert.deepEqual(errors,[]);console.log('PASS: unconfigured notice, denied-owner UI, sign-in, inline editing for all six worlds, independent headings, cloud adapter saves, conflict feedback, publication/logout separation, rollback and 4 responsive widths. Firebase service was mocked; server permissions were not tested by this browser check.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
